apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
spec:
  # using blank storage class names both here and within pvc will ensure the pvc matches this pv, and
  # avoid using the default storage class with dynamic volume provisioning
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/ssd/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs2
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/ssd/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs3
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/ssd/media
