---
# usage
# kubectl delete -f ./manifests/debug/pvc-debugger.yml
# kubectl apply -f ./manifests/debug/pvc-debugger.yml
# kubectl exec -it volume-debugger sh -n media
kind: Pod
apiVersion: v1
metadata:
  name: volume-debugger
  namespace: media
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000 # WARNING: performs a recursive "chown" and "chmod" on all files, which can cause timeouts. initContainer may be better
  # storageClassName: local-path-nfs
  containers:
  - name: debugger
    image: busybox
    command: ['sleep', '3600']
    resources: {}
    volumeMounts:
    - mountPath: "/data"
      name: volume-to-debug
    volumes:
      - name: volume-to-debug
        persistentVolumeClaim:
          claimName: nfs
