---
kind: Pod
apiVersion: v1
metadata:
  name: volume-debugger
  namespace: media
spec:
  volumes:
  - name: volume-to-debug
    persistentVolumeClaim:
      claimName: media-ssd
  containers:
  - name: debugger
    image: busybox
    command: ['sleep', '3600']
    volumeMounts:
    - mountPath: "/data"
      name: volume-to-debug
    resources: {}
