---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "nfs"
spec:
  storageClassName: local-path-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "40Gi"
