apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "nfs"
spec:
  # storageClassName: local-path-nfs
  accessModes:
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
