apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  # storageClassName: nfs
  storageClassName: ""
  capacity:
    # storage: 1Gi
    storage: 1Gi
  accessModes:
    # - ReadWriteMany # Access modes are defined below
    - ReadWriteOnce # Access modes are defined below
  # persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  nfs:
    server: 192.168.1.10 # Please change this to your NFS server
    path: /mnt/ssd/media # Please change this to the relevant share
